export const hotelTypes = [
  "Budget",
  "Luxury",
  "Semi Luxury",
  "Standard",
  "Suite",
  "Studio",
  "Villa",
  "Apartment",
  "Resort",
  "Cottage",
  "Bungalow",
  "Farm House",
  "Homestay",
  "Hostel",
  "Guest House",
  "Lodge",
  "Motel",
  "Dormitory",
  "Tree House",
  "Boat House",
  "Yacht",
  "Palace",
  "Mansion",
  "Castle",
];

export const ratings = [
  { label: "1 star", value: "1" },
  { label: "2 star", value: "2" },
  { label: "3 star", value: "3" },
  { label: "4 star", value: "4" },
  { label: "5 star", value: "5" },
];

export const amenities = [
  { id: "airCconditioning", label: "Air Conditioning" },
  { id: "airportShuttle", label: "Airport Shuttle" },
  { id: "bar", label: "Bar" },
  { id: "beachfront", label: "Beachfront" },
  { id: "breakfast", label: "Breakfast" },
  { id: "familyRooms", label: "Family Rooms" },
  { id: "fitnessCenter", label: "Fitness Center" },
  { id: "freeParking", label: "Free Parking" },
  { id: "freeWiFi", label: "Free WiFi" },
  { id: "non-smokingRooms", label: "Non-smoking Rooms" },
  { id: "petFriendly", label: "Pet Friendly" },
  { id: "restaurant", label: "Restaurant" },
  { id: "roomService", label: "Room Service" },
  { id: "spa", label: "Spa" },
  { id: "swimmingPool", label: "Swimming Pool" },
  { id: "tea/coffeeMaker", label: "Tea/Coffee Maker" },
  { id: "terrace", label: "Terrace" },
  { id: "view", label: "View" },
  { id: "washingMachine", label: "Washing Machine" },
];
